name: Test PR

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test GitHub Actions on PR
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-22.04 ]
    steps:
      - name: Run Hello World From Branch
        run: echo "hello world"
