name: Test PR 2

on:
  pull_request:
    branches: [ "db/test-wf2" ]

jobs:
  test:
    name: Test GitHub Actions on PR
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-22.04 ]
    steps:
      - name: Run Hello World from BRANCH 3
        run: echo "hello world"
